export { ReactComponent as HamburguerIcon } from './Hamburguer.svg'
export { ReactComponent as CancelIcon } from './Cancel.svg'
export { ReactComponent as SunIcon } from './Sun.svg'
export { ReactComponent as MoonIcon } from './Moon.svg'
export { ReactComponent as LinkedinIcon } from './Linkedin.svg'
export { ReactComponent as GithubIcon } from './Github.svg'
export { ReactComponent as LogoIcon } from './Logo.svg'
