export const experienceInfo = [
  {
    id: 1,
    position: 'Frontend Developer',
    company: 'Loka',
    location: 'USA (remote)',
    startDate: 'nov 2022',
    endDate: 'current',
    description: [
      'In this role I’m responsible for architecting and designing technical solutions for complex problems on the project.',
      'Basically in my day to day I usually review my colleagues PRs, pick some tickets on Jira to work on following the priority labels, participate on team meetings. I also create PRs for the bugs or features, fix comments and merge the approved ones.',
      'Tech used: HTML, CSS, Styled-components, Material UI, Reactjs, JavaScript, TypeScript, Redux Tool Kit, Jest, React Testing Library and Cypress.',
      'Currently I’m working on a banking web application for an American Credit Union.',
      'I also review PRs of my teammates and present demos to the clients',
    ],
    website: 'https://loka.com/',
  },
  {
    id: 2,
    position: 'Frontend Developer',
    company: 'Bridge351',
    location: 'Portugal (remote)',
    startDate: 'may 2022',
    endDate: 'nov 2022',
    description: [
      'I performed to develop web applications for customers using technologies such as HTML, CSS, Styled Components, Material UI, Reactjs, JavaScript and TypeScript.',
      'Had the opportunity to learn more about Redux Tool Kit, Jest, React Testing Library and Cypress',
    ],
    website: 'https://www.bridge351.com/',
  },
  {
    id: 3,
    position: 'Frontend Developer',
    company: 'Supernosso',
    location: 'Brazil (remote)',
    startDate: 'ago 2020',
    endDate: 'apr 2022',
    description: [
      'Performed maintenance, proposed improvements and developed new features in the e-commerce platform. Tech used: JavaScript, TypeScript, jQuery, ReactJS, HTML, CSS, Sass, Less and Vtex.',
      'Developed new features in Supernossoemcasa website.',
      'Participated of the whole redesign of Apoioentrega website improving the performance and UX.',
    ],
    website: 'https://www.supernosso.com/',
  },
  {
    id: 4,
    position: 'Web Developer',
    company: 'Obrazul',
    location: 'Brazil',
    startDate: 'mar 2020',
    endDate: 'jul 2020',
    description: [
      'Developed and promoted implementations in the company’s marketplace using technologies such as HTML, CSS, Sass, JavaScript, jQuery, Reactjs, Python, Django and PostegreSQL.',
      'Implemented and participated in the development of client’s dashboard and the result report generator.',
      'Using of Git as code version control system and Trello for project tasks management.',
    ],
    website: 'https://www.obrazul.com.br/',
  },
]
