name: AWS Static Web Apps CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build job
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: yarn install

      - name: build project
        run: yarn build